SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushHandler, [ %$Graze\Monolog\Handler\RaygunHandler ]]
  Graze\Monolog\Handler\RaygunHandler:
    constructor:
      RaygunClient: %$Raygun4php\RaygunClient
  Raygun4php\RaygunClient:
    factory: 'SilverStripe\Raygun\RaygunClientFactory'
