SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      - [ pushHandler, [ %$SilverStripe\Raygun\RaygunHandler ]]
  SilverStripe\Raygun\RaygunHandler:
    constructor:
      RaygunClient: %$Raygun4php\RaygunClient
  Raygun4php\RaygunClient:
    factory: 'SilverStripe\Raygun\RaygunClientFactory'
